name: Publish npm package to gitea
on:
  release:
    types: [published]
jobs:
  npm_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        # https://github.com/NomicFoundation/hardhat/issues/3877
      - name: Use Node.js 18.15
        uses: actions/setup-node@v3
        with:
          node-version: "18.15.0"
      - name: "Install dependencies and build packages"
        run: |
          cd ./nitro-protocol
          npm ci --legacy-peer-deps
      - name: Configure git.vdb.to npm registry
        run: |
          npm config set registry https://git.vdb.to/api/packages/cerc-io/npm/
      - name: Authenticate to git.vdb.to registry
        run: |
          npm config set -- '//git.vdb.to/api/packages/cerc-io/npm/:_authToken' "${{ secrets.GITEA_PUBLISH_TOKEN }}"
      - name: npm publish
        run: |
          cd ./nitro-protocol
          npm publish
